name: Build and Deploy React App
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
      
      - name: Install dependencies
        working-directory: ./ci-cd-react-app
        run: npm install
        
      - name: Set environment variable
        env:
          GIT_API_URL: ${{ secrets.GIT_API_URL }}
        run: |
          echo "GIT_API_URL=${GIT_API_URL}" >> ./.env

      - name : Build React App
        working-directory: ./ci-cd-react-app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #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
          branch: deploy # The branch the action should deploy to it.
          folder: ./ci-cd-react-app/build # The folder the action should deploy.
          single-commit: true

